// 七年级下册题库

const CHINESE_7L = [
  { id: '7l_c01', question: '《邓稼先》中邓稼先被誉为（  ）', options: ['A. 导弹之父', 'B. 两弹元勋', 'C. 航天之父', 'D. 氢弹之父'], answer: 'B', explanation: '邓稼先被称为"两弹元勋"。', knowledgePoint: '文学常识', subject: '语文' },
  { id: '7l_c02', question: '下列成语使用正确的是（  ）', options: ['A. 他侃侃而谈地说了两个小时。', 'B. 这件事让人出乎意料之外。', 'C. 我们要虚张声势地努力学习。', 'D. 他的演讲博得阵阵掌声。'], answer: 'D', explanation: 'A 重复；B 重复；C 贬义不当。', knowledgePoint: '成语', subject: '语文' },
  { id: '7l_c03', question: '《黄河颂》是组诗____的第二乐章', options: ['A. 长江大合唱', 'B. 黄河大合唱', 'C. 黄河协奏曲', 'D. 黄河交响曲'], answer: 'B', explanation: '光未然作词，冼星海作曲。', knowledgePoint: '文学常识', subject: '语文' },
  { id: '7l_c04', question: '下列句子没有语病的是（  ）', options: ['A. 通过努力，使他取得了好成绩。', 'B. 能否成功，关键在于坚持。', 'C. 教室里静悄悄的，没有一个人。', 'D. 我们要发扬并继承优良传统。'], answer: 'C', explanation: 'A 缺主语；B 两面对一面；D 语序不当。', knowledgePoint: '病句', subject: '语文' },
  { id: '7l_c05', question: '"木兰当户织"中"当"的意思是（  ）', options: ['A. 应当', 'B. 面对', 'C. 当作', 'D. 当然'], answer: 'B', explanation: '"当户织"即面对门织布。', knowledgePoint: '文言词汇', subject: '语文' },
  { id: '7l_c06', question: '《卖油翁》的作者是（  ）', options: ['A. 欧阳修', 'B. 王安石', 'C. 苏轼', 'D. 曾巩'], answer: 'A', explanation: '欧阳修，唐宋八大家之一。', knowledgePoint: '文学常识', subject: '语文' },
  { id: '7l_c07', question: '"但手熟尔"中"尔"的意思是（  ）', options: ['A. 你', 'B. 罢了', 'C. 如此', 'D. 然后'], answer: 'B', explanation: '"尔"同"耳"，相当于"罢了"。', knowledgePoint: '文言词汇', subject: '语文' },
  { id: '7l_c08', question: '下列词语书写正确的是（  ）', options: ['A. 锋芒必露', 'B. 妇儒皆知', 'C. 可歌可泣', 'D. 鞠躬尽粹'], answer: 'C', explanation: 'A"毕"；B"孺"；D"瘁"。', knowledgePoint: '字形', subject: '语文' },
  { id: '7l_c09', question: '《孙权劝学》选自（  ）', options: ['A. 《史记》', 'B. 《资治通鉴》', 'C. 《汉书》', 'D. 《战国策》'], answer: 'B', explanation: '司马光主编的《资治通鉴》。', knowledgePoint: '文学常识', subject: '语文' },
  { id: '7l_c10', question: '"士别三日，即更刮目相待"意味着（  ）', options: ['A. 三天不见要重新认识', 'B. 人要不断进步', 'C. 时间过得快', 'D. 友谊很重要'], answer: 'B', explanation: '比喻人不断进步，不能用老眼光看人。', knowledgePoint: '文言理解', subject: '语文' },
  { id: '7l_c11', question: '下列加点字读音相同的是（  ）', options: ['A. 校对/学校', 'B. 要求/重要', 'C. 供应/供认', 'D. 和面/和平'], answer: 'B', explanation: '都读 yào。', knowledgePoint: '多音字', subject: '语文' },
  { id: '7l_c12', question: '《最后一课》的作者是（  ）', options: ['A. 英国', 'B. 法国', 'C. 德国', 'D. 俄国'], answer: 'B', explanation: '法国作家都德。', knowledgePoint: '文学常识', subject: '语文' },
  { id: '7l_c13', question: '下列句子是被动句的是（  ）', options: ['A. 他被老师表扬了。', 'B. 他表扬了老师。', 'C. 老师表扬他。', 'D. 他和老师。'], answer: 'A', explanation: '"被"字表示被动。', knowledgePoint: '句式', subject: '语文' },
  { id: '7l_c14', question: '《阿长与<山海经>》中阿长是（  ）', options: ['A. 作者的保姆', 'B. 作者的老师', 'C. 作者的邻居', 'D. 作者的亲戚'], answer: 'A', explanation: '阿长是鲁迅儿时的保姆。', knowledgePoint: '文学常识', subject: '语文' },
  { id: '7l_c15', question: '下列修辞手法判断正确的是（  ）', options: ['A. "他跑得比箭还快"—夸张', 'B. "花儿在微笑"—比喻', 'C. "书是人类进步的阶梯"—拟人', 'D. "盘古开天地"—排比'], answer: 'A', explanation: 'A 是夸张；B 是拟人；C 是比喻。', knowledgePoint: '修辞', subject: '语文' },
  { id: '7l_c16', question: '《木兰诗》是（  ）', options: ['A. 唐诗', 'B. 宋词', 'C. 北朝民歌', 'D. 汉乐府'], answer: 'C', explanation: '北朝民歌，与《孔雀东南飞》并称"乐府双璧"。', knowledgePoint: '文学常识', subject: '语文' },
  { id: '7l_c17', question: '"万里赴戎机"中"戎机"的意思是（  ）', options: ['A. 军事', 'B. 战场', 'C. 战争', 'D. 军队'], answer: 'A', explanation: '"戎机"指战争、军事。', knowledgePoint: '文言词汇', subject: '语文' },
  { id: '7l_c18', question: '下列句子表肯定语气的是（  ）', options: ['A. 难道不是吗？', 'B. 也许是吧。', 'C. 大概如此。', 'D. 可能这样。'], answer: 'A', explanation: '反问句表达肯定的意思。', knowledgePoint: '句式', subject: '语文' },
  { id: '7l_c19', question: '《老王》的作者是（  ）', options: ['A. 鲁迅', 'B. 巴金', 'C. 杨绛', 'D. 冰心'], answer: 'C', explanation: '杨绛，钱钟书夫人。', knowledgePoint: '文学常识', subject: '语文' },
  { id: '7l_c20', question: '下列词语感情色彩不同的是（  ）', options: ['A. 奋不顾身', 'B. 见义勇为', 'C. 铤而走险', 'D. 舍己为人'], answer: 'C', explanation: 'C 是贬义，其余是褒义。', knowledgePoint: '词语色彩', subject: '语文' },
  { id: '7l_c21', question: '《台阶》一文中，父亲修台阶是为了（  ）', options: ['A. 方便走路', 'B. 提高地位', 'C. 增加收入', 'D. 美化环境'], answer: 'B', explanation: '台阶高代表地位高。', knowledgePoint: '阅读理解', subject: '语文' },
  { id: '7l_c22', question: '下列关联词使用正确的是（  ）', options: ['A. 虽然下雨，因此我不去了。', 'B. 因为下雨，所以我不去了。', 'C. 即使下雨，但是我不去了。', 'D. 如果下雨，然而我不去了。'], answer: 'B', explanation: '因果关系用"因为...所以..."。', knowledgePoint: '关联词', subject: '语文' },
  { id: '7l_c23', question: '《叶圣陶先生二三事》中，叶圣陶的身份是（  ）', options: ['A. 作家', 'B. 教育家', 'C. 编辑家', 'D. 以上都是'], answer: 'D', explanation: '叶圣陶是作家、教育家、编辑家。', knowledgePoint: '文学常识', subject: '语文' },
  { id: '7l_c24', question: '下列句子是疑问句的是（  ）', options: ['A. 你去吗？', 'B. 你来了。', 'C. 真好看！', 'D. 快走吧。'], answer: 'A', explanation: '疑问句用问号。', knowledgePoint: '句式', subject: '语文' },
  { id: '7l_c25', question: '《驿路梨花》中"梨花"是（  ）', options: ['A. 一种花', 'B. 一个人名', 'C. 一个地名', 'D. 既是花也是人名'], answer: 'D', explanation: '既指梨花，也指叫梨花的小姑娘。', knowledgePoint: '阅读理解', subject: '语文' },
  { id: '7l_c26', question: '下列成语与人物对应错误的是（  ）', options: ['A. 闻鸡起舞—祖逖', 'B. 凿壁偷光—匡衡', 'C. 囊萤映雪—车胤', 'D. 悬梁刺股—李白'], answer: 'D', explanation: '悬梁刺股是孙敬和苏秦。', knowledgePoint: '成语', subject: '语文' },
  { id: '7l_c27', question: '《紫藤萝瀑布》运用的主要表现手法是（  ）', options: ['A. 借景抒情', 'B. 直抒胸臆', 'C. 对比衬托', 'D. 欲扬先抑'], answer: 'A', explanation: '借紫藤萝抒发对生命的感悟。', knowledgePoint: '表现手法', subject: '语文' },
  { id: '7l_c28', question: '下列句子是祈使句的是（  ）', options: ['A. 你快来！', 'B. 你来了吗？', 'C. 你来了。', 'D. 你真好！'], answer: 'A', explanation: '祈使句表示请求、命令。', knowledgePoint: '句式', subject: '语文' },
  { id: '7l_c29', question: '《伟大的悲剧》中"悲剧"指的是（  ）', options: ['A. 戏剧类型', 'B. 斯科特探险队的遭遇', 'C. 南极探险本身', 'D. 作者的心情'], answer: 'B', explanation: '指斯科特探险队虽失败但精神伟大。', knowledgePoint: '阅读理解', subject: '语文' },
  { id: '7l_c30', question: '下列诗句描写春天的是（  ）', options: ['A. 接天莲叶无穷碧', 'B. 几处早莺争暖树', 'C. 停车坐爱枫林晚', 'D. 孤舟蓑笠翁'], answer: 'B', explanation: '出自白居易《钱塘湖春行》。', knowledgePoint: '古诗词', subject: '语文' }
];

const MATH_7L = [
  { id: '7l_m01', question: '点 P(3,-2) 位于（  ）', options: ['A. 第一象限', 'B. 第二象限', 'C. 第三象限', 'D. 第四象限'], answer: 'D', explanation: '横坐标正，纵坐标负，在第四象限。', knowledgePoint: '平面直角坐标系', subject: '数学' },
  { id: '7l_m02', question: '下列是二元一次方程的是（  ）', options: ['A. x+y=5', 'B. x²+y=3', 'C. xy=6', 'D. x+1/y=2'], answer: 'A', explanation: '两个未知数，次数都是 1 的整式方程。', knowledgePoint: '二元一次方程', subject: '数学' },
  { id: '7l_m03', question: '方程组 x+y=5, x-y=1 的解是（  ）', options: ['A. x=2,y=3', 'B. x=3,y=2', 'C. x=4,y=1', 'D. x=1,y=4'], answer: 'B', explanation: '两式相加得 2x=6,x=3，代入得 y=2。', knowledgePoint: '解方程组', subject: '数学' },
  { id: '7l_m04', question: '下列线段能组成三角形的是（  ）', options: ['A. 3,4,8', 'B. 5,6,10', 'C. 2,3,6', 'D. 4,5,9'], answer: 'B', explanation: '5+6>10，满足三角形三边关系。', knowledgePoint: '三角形', subject: '数学' },
  { id: '7l_m05', question: '三角形内角和等于（  ）', options: ['A. 90°', 'B. 180°', 'C. 270°', 'D. 360°'], answer: 'B', explanation: '三角形内角和定理为 180°。', knowledgePoint: '三角形', subject: '数学' },
  { id: '7l_m06', question: '若 a>b，则下列不等式成立的是（  ）', options: ['A. a+2<b+2', 'B. a-3<b-3', 'C. 2a>2b', 'D. -a>-b'], answer: 'C', explanation: '不等式两边乘正数，不等号方向不变。', knowledgePoint: '不等式', subject: '数学' },
  { id: '7l_m07', question: '点 A(2,3) 关于 x 轴对称的点是（  ）', options: ['A. (2,-3)', 'B. (-2,3)', 'C. (-2,-3)', 'D. (3,2)'], answer: 'A', explanation: '关于 x 轴对称，横坐标不变，纵坐标相反。', knowledgePoint: '轴对称', subject: '数学' },
  { id: '7l_m08', question: '√16 的值是（  ）', options: ['A. 4', 'B. -4', 'C. ±4', 'D. 8'], answer: 'A', explanation: '算术平方根是非负的。', knowledgePoint: '平方根', subject: '数学' },
  { id: '7l_m09', question: '下列是无理数的是（  ）', options: ['A. 3.14', 'B. √2', 'C. 22/7', 'D. 0.333'], answer: 'B', explanation: '√2 是无限不循环小数。', knowledgePoint: '实数', subject: '数学' },
  { id: '7l_m10', question: '在平面直角坐标系中，原点的坐标是（  ）', options: ['A. (0,0)', 'B. (1,1)', 'C. (0,1)', 'D. (1,0)'], answer: 'A', explanation: '原点是 (0,0)。', knowledgePoint: '坐标系', subject: '数学' },
  { id: '7l_m11', question: '三角形的外角等于（  ）', options: ['A. 与它相邻的内角', 'B. 与它不相邻的两个内角之和', 'C. 90°', 'D. 180°'], answer: 'B', explanation: '三角形外角定理。', knowledgePoint: '三角形', subject: '数学' },
  { id: '7l_m12', question: '方程 2x+3y=6，当 x=0 时，y=（  ）', options: ['A. 0', 'B. 1', 'C. 2', 'D. 3'], answer: 'C', explanation: '代入 x=0，3y=6，y=2。', knowledgePoint: '二元一次方程', subject: '数学' },
  { id: '7l_m13', question: '下列图形中，具有稳定性的图形是（  ）', options: ['A. 四边形', 'B. 三角形', 'C. 五边形', 'D. 六边形'], answer: 'B', explanation: '三角形具有稳定性。', knowledgePoint: '三角形', subject: '数学' },
  { id: '7l_m14', question: '点 P(-3,4) 到 x 轴的距离是（  ）', options: ['A. 3', 'B. 4', 'C. 5', 'D. 7'], answer: 'B', explanation: '到 x 轴距离等于纵坐标的绝对值。', knowledgePoint: '坐标系', subject: '数学' },
  { id: '7l_m15', question: '√81 的平方根是（  ）', options: ['A. 9', 'B. 3', 'C. ±3', 'D. ±9'], answer: 'C', explanation: '√81=9，9 的平方根是±3。', knowledgePoint: '平方根', subject: '数学' },
  { id: '7l_m16', question: '不等式 x>3 的解集在数轴上表示为（  ）', options: ['A. 3 右边的所有点', 'B. 3 左边的所有点', 'C. 只有 3 这个点', 'D. 3 两边的点'], answer: 'A', explanation: '>表示大于，在右边。', knowledgePoint: '不等式', subject: '数学' },
  { id: '7l_m17', question: '下列各数中，最小的是（  ）', options: ['A. -√5', 'B. -2', 'C. -3', 'D. -√10'], answer: 'D', explanation: '√10≈3.16，所以 -√10 最小。', knowledgePoint: '实数比较', subject: '数学' },
  { id: '7l_m18', question: '等腰三角形两边长为 3 和 7，周长是（  ）', options: ['A. 13', 'B. 17', 'C. 13 或 17', 'D. 无法确定'], answer: 'B', explanation: '若腰为 3，则 3+3<7，不构成三角形；腰为 7，周长=7+7+3=17。', knowledgePoint: '三角形', subject: '数学' },
  { id: '7l_m19', question: '方程组 x+y=10,x-y=4 的解是（  ）', options: ['A. x=7,y=3', 'B. x=6,y=4', 'C. x=5,y=5', 'D. x=8,y=2'], answer: 'A', explanation: '两式相加：2x=14,x=7，代入得 y=3。', knowledgePoint: '方程组', subject: '数学' },
  { id: '7l_m20', question: '点 (0,-5) 在（  ）', options: ['A. x 轴上', 'B. y 轴上', 'C. 原点', 'D. 第一象限'], answer: 'B', explanation: '横坐标为 0，在 y 轴上。', knowledgePoint: '坐标系', subject: '数学' },
  { id: '7l_m21', question: '下列命题是真命题的是（  ）', options: ['A. 同位角相等', 'B. 对顶角相等', 'C. 相等的角是对顶角', 'D. 互补的角是邻补角'], answer: 'B', explanation: '对顶角一定相等。', knowledgePoint: '命题', subject: '数学' },
  { id: '7l_m22', question: '不等式 -2x>6 的解集是（  ）', options: ['A. x>-3', 'B. x<-3', 'C. x>3', 'D. x<3'], answer: 'B', explanation: '两边除以 -2，不等号方向改变。', knowledgePoint: '解不等式', subject: '数学' },
  { id: '7l_m23', question: '√2+√3=（  ）', options: ['A. √5', 'B. √6', 'C. 无法合并', 'D. 2√5'], answer: 'C', explanation: '不是同类二次根式，不能合并。', knowledgePoint: '二次根式', subject: '数学' },
  { id: '7l_m24', question: '三角形的高（  ）', options: ['A. 一定在三角形内部', 'B. 一定在三角形外部', 'C. 可能在边上', 'D. 以上都不对'], answer: 'C', explanation: '锐角三角形在内部，直角三角形在边上，钝角三角形在外部。', knowledgePoint: '三角形', subject: '数学' },
  { id: '7l_m25', question: '点 A(1,2) 平移后得到 A\'(4,6)，平移向量是（  ）', options: ['A. (3,4)', 'B. (4,2)', 'C. (3,2)', 'D. (4,4)'], answer: 'A', explanation: '横坐标 +3，纵坐标 +4。', knowledgePoint: '平移', subject: '数学' },
  { id: '7l_m26', question: '下列计算正确的是（  ）', options: ['A. √4+√9=√13', 'B. √4×√9=6', 'C. √16-√4=2', 'D. √2+√2=2'], answer: 'B', explanation: '√4×√9=2×3=6。', knowledgePoint: '二次根式', subject: '数学' },
  { id: '7l_m27', question: '多边形的内角和公式是（  ）', options: ['A. (n-2)×180°', 'B. n×180°', 'C. (n+2)×180°', 'D. n×360°'], answer: 'A', explanation: 'n 边形内角和=(n-2)×180°。', knowledgePoint: '多边形', subject: '数学' },
  { id: '7l_m28', question: '方程 x²=4 的解是（  ）', options: ['A. x=2', 'B. x=-2', 'C. x=±2', 'D. x=4'], answer: 'C', explanation: '平方等于 4 的数有 2 和 -2。', knowledgePoint: '平方根', subject: '数学' },
  { id: '7l_m29', question: '下列命题的逆命题是真命题的是（  ）', options: ['A. 对顶角相等', 'B. 全等三角形的对应角相等', 'C. 两直线平行，同位角相等', 'D. 若 a=b，则 a²=b²'], answer: 'C', explanation: '同位角相等，两直线平行。', knowledgePoint: '命题', subject: '数学' },
  { id: '7l_m30', question: '五边形的内角和是（  ）', options: ['A. 360°', 'B. 540°', 'C. 720°', 'D. 900°'], answer: 'B', explanation: '(5-2)×180°=540°。', knowledgePoint: '多边形', subject: '数学' }
];

const ENGLISH_7L = [
  { id: '7l_e01', question: '— ____ did you go to school?\n— I walked.', options: ['A. What', 'B. How', 'C. When', 'D. Where'], answer: 'B', explanation: '询问方式用 How。', knowledgePoint: '疑问词', subject: '英语' },
  { id: '7l_e02', question: 'Yesterday I ____ to the park.', options: ['A. go', 'B. went', 'C. goes', 'D. going'], answer: 'B', explanation: 'yesterday 用一般过去时。', knowledgePoint: '过去时', subject: '英语' },
  { id: '7l_e03', question: '— ____ was your weekend?\n— It was great.', options: ['A. What', 'B. How', 'C. When', 'D. Where'], answer: 'B', explanation: '询问情况用 How。', knowledgePoint: '疑问词', subject: '英语' },
  { id: '7l_e04', question: 'She ____ her homework last night.', options: ['A. do', 'B. does', 'C. did', 'D. doing'], answer: 'C', explanation: 'last night 用过去时。', knowledgePoint: '过去时', subject: '英语' },
  { id: '7l_e05', question: 'There ____ a lot of people at the party.', options: ['A. is', 'B. are', 'C. was', 'D. were'], answer: 'B', explanation: 'people 是复数，用 are。', knowledgePoint: 'there be', subject: '英语' },
  { id: '7l_e06', question: '— What ____ you do on Sunday?\n— I read a book.', options: ['A. do', 'B. does', 'C. did', 'D. doing'], answer: 'C', explanation: '询问过去的事情用 did。', knowledgePoint: '过去时', subject: '英语' },
  { id: '7l_e07', question: 'The weather is ____ today.', options: ['A. sun', 'B. sunny', 'C. suny', 'D. suns'], answer: 'B', explanation: '形容词 sunny 描述天气。', knowledgePoint: '形容词', subject: '英语' },
  { id: '7l_e08', question: '— ____ did he go?\n— To London.', options: ['A. What', 'B. Where', 'C. When', 'D. Who'], answer: 'B', explanation: '询问地点用 Where。', knowledgePoint: '疑问词', subject: '英语' },
  { id: '7l_e09', question: 'He is ____ than his brother.', options: ['A. tall', 'B. taller', 'C. tallest', 'D. the tall'], answer: 'B', explanation: '比较级用 taller。', knowledgePoint: '比较级', subject: '英语' },
  { id: '7l_e10', question: 'They ____ play soccer after school.', options: ['A. use to', 'B. used to', 'C. using to', 'D. uses to'], answer: 'B', explanation: 'used to 表示过去常常。', knowledgePoint: 'used to', subject: '英语' },
  { id: '7l_e11', question: '— How was your trip?\n— It was ____. ', options: ['A. bore', 'B. bored', 'C. boring', 'D. bores'], answer: 'C', explanation: '描述事物用 boring。', knowledgePoint: '形容词', subject: '英语' },
  { id: '7l_e12', question: 'My father ____ to work by car.', options: ['A. go', 'B. goes', 'C. went', 'D. going'], answer: 'B', explanation: '一般现在时，第三人称单数用 goes。', knowledgePoint: '一般现在时', subject: '英语' },
  { id: '7l_e13', question: '— ____ are you?\n— I\'m 160 cm tall.', options: ['A. How old', 'B. How tall', 'C. How heavy', 'D. How long'], answer: 'B', explanation: '询问身高用 How tall。', knowledgePoint: '疑问词', subject: '英语' },
  { id: '7l_e14', question: 'She is ____ student in our class.', options: ['A. good', 'B. better', 'C. best', 'D. the best'], answer: 'D', explanation: '最高级用 the best。', knowledgePoint: '最高级', subject: '英语' },
  { id: '7l_e15', question: 'We should ____ our classroom clean.', options: ['A. keep', 'B. kept', 'C. keeping', 'D. keeps'], answer: 'A', explanation: 'should 后接动词原形。', knowledgePoint: '情态动词', subject: '英语' },
  { id: '7l_e16', question: '— Can you swim?\n— ____. ', options: ['A. Yes, I can.', 'B. Yes, I do.', 'C. No, I don\'t.', 'D. Yes, I am.'], answer: 'A', explanation: 'Can 提问，Can 回答。', knowledgePoint: 'can 句型', subject: '英语' },
  { id: '7l_e17', question: 'It\'s time ____ to school.', options: ['A. go', 'B. to go', 'C. going', 'D. went'], answer: 'B', explanation: 'It\'s time to do sth.固定搭配。', knowledgePoint: '句型', subject: '英语' },
  { id: '7l_e18', question: '— ____ do you like pandas?\n— Because they\'re cute.', options: ['A. What', 'B. Why', 'C. When', 'D. Where'], answer: 'B', explanation: '询问原因用 Why。', knowledgePoint: '疑问词', subject: '英语' },
  { id: '7l_e19', question: 'I\'m ____ than you.', options: ['A. heavy', 'B. heavier', 'C. heaviest', 'D. the heaviest'], answer: 'B', explanation: '比较级用 heavier。', knowledgePoint: '比较级', subject: '英语' },
  { id: '7l_e20', question: 'She ____ TV at the moment.', options: ['A. watch', 'B. watches', 'C. is watching', 'D. watched'], answer: 'C', explanation: 'at the moment 用现在进行时。', knowledgePoint: '现在进行时', subject: '英语' },
  { id: '7l_e21', question: '— What\'s the ____ like today?\n— It\'s sunny.', options: ['A. day', 'B. date', 'C. weather', 'D. time'], answer: 'C', explanation: '询问天气用 What\'s the weather like。', knowledgePoint: '天气句型', subject: '英语' },
  { id: '7l_e22', question: 'They enjoy ____ basketball.', options: ['A. play', 'B. playing', 'C. to play', 'D. played'], answer: 'B', explanation: 'enjoy doing sth.固定搭配。', knowledgePoint: '动词用法', subject: '英语' },
  { id: '7l_e23', question: '— How many ____ are there?\n— There are five. ', options: ['A. book', 'B. books', 'C. a book', 'D. the book'], answer: 'B', explanation: 'How many 后接可数名词复数。', knowledgePoint: '名词复数', subject: '英语' },
  { id: '7l_e24', question: 'My parents are strict ____ me.', options: ['A. in', 'B. on', 'C. with', 'D. at'], answer: 'C', explanation: 'be strict with sb.对某人严格。', knowledgePoint: '介词', subject: '英语' },
  { id: '7l_e25', question: '— Would you like some tea?\n— ____.', options: ['A. Yes, please.', 'B. Yes, I would.', 'C. No, I wouldn\'t.', 'D. No, I don\'t.'], answer: 'A', explanation: '礼貌回答用 Yes, please. ', knowledgePoint: '交际用语', subject: '英语' },
  { id: '7l_e26', question: 'He stopped ____ a rest.', options: ['A. have', 'B. having', 'C. to have', 'D. had'], answer: 'C', explanation: 'stop to do sth.停下来去做某事。', knowledgePoint: '动词用法', subject: '英语' },
  { id: '7l_e27', question: 'The boy ____ blue is my brother.', options: ['A. in', 'B. on', 'C. at', 'D. with'], answer: 'A', explanation: '穿什么颜色用 in。', knowledgePoint: '介词', subject: '英语' },
  { id: '7l_e28', question: '— Let\'s play soccer.\n— That sounds ____. ', options: ['A. good', 'B. well', 'C. fine', 'D. great'], answer: 'A', explanation: 'sound good 听起来不错。', knowledgePoint: '系动词', subject: '英语' },
  { id: '7l_e29', question: 'I have ____ friends.', options: ['A. much', 'B. many', 'C. a lot', 'D. lot of'], answer: 'B', explanation: 'friends 可数，用 many。', knowledgePoint: '量词', subject: '英语' },
  { id: '7l_e30', question: 'Please ____ quiet in the library.', options: ['A. is', 'B. are', 'C. be', 'D. am'], answer: 'C', explanation: '祈使句用动词原形。', knowledgePoint: '祈使句', subject: '英语' }
];

const SCIENCE_7L = [
  { id: '7l_s01', question: '下列不能作为证据的是（  ）', options: ['A. 实验数据', 'B. 观察现象', 'C. 个人猜测', 'D. 文献资料'], answer: 'C', explanation: '科学需要客观证据。', knowledgePoint: '科学方法', subject: '科学' },
  { id: '7l_s02', question: '种子萌发不需要的条件是（  ）', options: ['A. 适宜的温度', 'B. 适量的水分', 'C. 充足的空气', 'D. 阳光'], answer: 'D', explanation: '大多数种子萌发不需要阳光。', knowledgePoint: '植物', subject: '科学' },
  { id: '7l_s03', question: '下列属于化学性质的是（  ）', options: ['A. 颜色', 'B. 气味', 'C. 可燃性', 'D. 熔点'], answer: 'C', explanation: '可燃性需要化学变化才能表现出来。', knowledgePoint: '物质性质', subject: '科学' },
  { id: '7l_s04', question: '下列物质中属于纯净物的是（  ）', options: ['A. 空气', 'B. 海水', 'C. 氧气', 'D. 糖水'], answer: 'C', explanation: '氧气只由一种物质组成。', knowledgePoint: '物质分类', subject: '科学' },
  { id: '7l_s05', question: '人体消化食物的主要器官是（  ）', options: ['A. 口腔', 'B. 胃', 'C. 小肠', 'D. 大肠'], answer: 'C', explanation: '小肠是消化和吸收的主要场所。', knowledgePoint: '消化系统', subject: '科学' },
  { id: '7l_s06', question: '下列动物属于哺乳动物的是（  ）', options: ['A. 鲫鱼', 'B. 家鸽', 'C. 家兔', 'D. 青蛙'], answer: 'C', explanation: '家兔胎生、哺乳。', knowledgePoint: '动物分类', subject: '科学' },
  { id: '7l_s07', question: '光在真空中的传播速度约为（  ）', options: ['A. 340m/s', 'B. 3×10^8m/s', 'C. 3×10^5m/s', 'D. 3×10^6m/s'], answer: 'B', explanation: '光速约为 3×10^8 米每秒。', knowledgePoint: '光速', subject: '科学' },
  { id: '7l_s08', question: '下列做法有利于环境保护的是（  ）', options: ['A. 焚烧垃圾', 'B. 使用一次性筷子', 'C. 垃圾分类回收', 'D. 大量使用农药'], answer: 'C', explanation: '垃圾分类有利于资源回收。', knowledgePoint: '环境保护', subject: '科学' },
  { id: '7l_s09', question: '植物的根主要作用是（  ）', options: ['A. 光合作用', 'B. 吸收水分和无机盐', 'C. 蒸腾作用', 'D. 繁殖'], answer: 'B', explanation: '根吸收水分和无机盐。', knowledgePoint: '植物', subject: '科学' },
  { id: '7l_s10', question: '下列变化属于物理变化的是（  ）', options: ['A. 铁生锈', 'B. 纸燃烧', 'C. 水结冰', 'D. 食物腐烂'], answer: 'C', explanation: '水结冰没有新物质生成。', knowledgePoint: '物质变化', subject: '科学' },
  { id: '7l_s11', question: '正常情况下，人的脉搏每分钟约跳（  ）', options: ['A. 20 次', 'B. 50 次', 'C. 75 次', 'D. 150 次'], answer: 'C', explanation: '成年人安静时心率约 60-100 次/分钟。', knowledgePoint: '人体生理', subject: '科学' },
  { id: '7l_s12', question: '下列不属于能量的是（  ）', options: ['A. 机械能', 'B. 热能', 'C. 电能', 'D. 速度'], answer: 'D', explanation: '速度不是能量形式。', knowledgePoint: '能量', subject: '科学' },
  { id: '7l_s13', question: '植物进行光合作用的场所是（  ）', options: ['A. 细胞核', 'B. 叶绿体', 'C. 线粒体', 'D. 液泡'], answer: 'B', explanation: '叶绿体是光合作用的场所。', knowledgePoint: '细胞', subject: '科学' },
  { id: '7l_s14', question: '下列气体中，能支持燃烧的是（  ）', options: ['A. 氮气', 'B. 氧气', 'C. 二氧化碳', 'D. 稀有气体'], answer: 'B', explanation: '氧气具有助燃性。', knowledgePoint: '空气', subject: '科学' },
  { id: '7l_s15', question: '人体最大的消化腺是（  ）', options: ['A. 唾液腺', 'B. 肝脏', 'C. 胰腺', 'D. 胃腺'], answer: 'B', explanation: '肝脏是最大的消化腺。', knowledgePoint: '消化系统', subject: '科学' },
  { id: '7l_s16', question: '声音在下列介质中传播最慢的是（  ）', options: ['A. 空气', 'B. 水', 'C. 钢铁', 'D. 玻璃'], answer: 'A', explanation: '气体传播声音最慢。', knowledgePoint: '声音', subject: '科学' },
  { id: '7l_s17', question: '下列属于可再生资源的是（  ）', options: ['A. 煤炭', 'B. 石油', 'C. 太阳能', 'D. 天然气'], answer: 'C', explanation: '太阳能取之不尽。', knowledgePoint: '资源', subject: '科学' },
  { id: '7l_s18', question: '水的沸点是（  ）', options: ['A. 90℃', 'B. 100℃', 'C. 110℃', 'D. 80℃'], answer: 'B', explanation: '标准大气压下水的沸点是 100℃。', knowledgePoint: '物态变化', subject: '科学' },
  { id: '7l_s19', question: '下列不属于昆虫特征的是（  ）', options: ['A. 身体分为头胸腹', 'B. 三对足', 'C. 一般有翅', 'D. 用肺呼吸'], answer: 'D', explanation: '昆虫用气管呼吸。', knowledgePoint: '动物分类', subject: '科学' },
  { id: '7l_s20', question: '地球绕太阳公转的周期约是（  ）', options: ['A. 1 天', 'B. 1 个月', 'C. 1 年', 'D. 10 年'], answer: 'C', explanation: '公转周期约 365 天。', knowledgePoint: '地球运动', subject: '科学' },
  { id: '7l_s21', question: '下列不属于传染病的是（  ）', options: ['A. 流感', 'B. 肺结核', 'C. 糖尿病', 'D. 新冠肺炎'], answer: 'C', explanation: '糖尿病是代谢疾病。', knowledgePoint: '健康', subject: '科学' },
  { id: '7l_s22', question: '植物蒸腾作用的主要器官是（  ）', options: ['A. 根', 'B. 茎', 'C. 叶', 'D. 花'], answer: 'C', explanation: '叶是蒸腾作用的主要器官。', knowledgePoint: '植物', subject: '科学' },
  { id: '7l_s23', question: '人体呼吸系统中进行气体交换的场所是（  ）', options: ['A. 气管', 'B. 支气管', 'C. 肺', 'D. 肺泡'], answer: 'D', explanation: '肺泡是气体交换的场所。', knowledgePoint: '呼吸系统', subject: '科学' },
  { id: '7l_s24', question: '下列属于省力杠杆的是（  ）', options: ['A. 镊子', 'B. 筷子', 'C. 钓鱼竿', 'D. 撬棍'], answer: 'D', explanation: '撬棍动力臂大于阻力臂。', knowledgePoint: '简单机械', subject: '科学' },
  { id: '7l_s25', question: '白天我们看到天空是蓝色的主要原因是（  ）', options: ['A. 天空的颜色', 'B. 光的散射', 'C. 大气污染', 'D. 海洋反射'], answer: 'B', explanation: '大气散射蓝光较多。', knowledgePoint: '光学', subject: '科学' },
  { id: '7l_s26', question: '下列不属于生命特征的是（  ）', options: ['A. 新陈代谢', 'B. 生长繁殖', 'C. 遗传变异', 'D. 固定位置'], answer: 'D', explanation: '生物可以移动位置。', knowledgePoint: '生物特征', subject: '科学' },
  { id: '7l_s27', question: '人体血液循环的动力器官是（  ）', options: ['A. 血管', 'B. 心脏', 'C. 肺', 'D. 肝脏'], answer: 'B', explanation: '心脏是血液循环的动力器官。', knowledgePoint: '循环系统', subject: '科学' },
  { id: '7l_s28', question: '下列物质常温下是液体的是（  ）', options: ['A. 氧气', 'B. 铁', 'C. 水', 'D. 二氧化碳'], answer: 'C', explanation: '水在常温下是液体。', knowledgePoint: '物质状态', subject: '科学' },
  { id: '7l_s29', question: '食物的主要能量来源是（  ）', options: ['A. 维生素', 'B. 无机盐', 'C. 糖类', 'D. 水'], answer: 'C', explanation: '糖类是主要的能量来源。', knowledgePoint: '营养', subject: '科学' },
  { id: '7l_s30', question: '我们应"低碳生活"主要是减少（  ）排放', options: ['A. 氧气', 'B. 氮气', 'C. 二氧化碳', 'D. 水蒸气'], answer: 'C', explanation: '低碳生活指减少二氧化碳排放。', knowledgePoint: '环境保护', subject: '科学' }
];

const SOCIAL_7L = [
  { id: '7l_so01', question: '我国领土最北端在（  ）', options: ['A. 黑龙江省漠河县', 'B. 黑龙江省黑河市', 'C. 新疆帕米尔高原', 'D. 海南省曾母暗沙'], answer: 'A', explanation: '最北端在黑龙江省漠河县北端的黑龙江主航道中心线上。', knowledgePoint: '中国疆域', subject: '社会' },
  { id: '7l_so02', question: '我国共有____个省级行政区（  ）', options: ['A. 32', 'B. 33', 'C. 34', 'D. 35'], answer: 'C', explanation: '23 个省、5 个自治区、4 个直辖市、2 个特别行政区。', knowledgePoint: '行政区划', subject: '社会' },
  { id: '7l_so03', question: '我国人口最多的民族是（  ）', options: ['A. 壮族', 'B. 汉族', 'C. 回族', 'D. 满族'], answer: 'B', explanation: '汉族占全国人口的 91% 以上。', knowledgePoint: '民族', subject: '社会' },
  { id: '7l_so04', question: '我国地势特点是（  ）', options: ['A. 西高东低', 'B. 东高西低', 'C. 南高北低', 'D. 北高南低'], answer: 'A', explanation: '我国地势西高东低，呈阶梯状分布。', knowledgePoint: '地形', subject: '社会' },
  { id: '7l_so05', question: '我国最长的河流是（  ）', options: ['A. 黄河', 'B. 长江', 'C. 珠江', 'D. 黑龙江'], answer: 'B', explanation: '长江全长 6300 多千米，是我国第一长河。', knowledgePoint: '河流', subject: '社会' },
  { id: '7l_so06', question: '我国气候的主要特征是（  ）', options: ['A. 单一性', 'B. 复杂性多样性', 'C. 寒冷干燥', 'D. 炎热多雨'], answer: 'B', explanation: '气候复杂多样，季风气候显著。', knowledgePoint: '气候', subject: '社会' },
  { id: '7l_so07', question: '我国最大的淡水湖是（  ）', options: ['A. 洞庭湖', 'B. 鄱阳湖', 'C. 太湖', 'D. 洪泽湖'], answer: 'B', explanation: '鄱阳湖位于江西省，是我国最大淡水湖。', knowledgePoint: '湖泊', subject: '社会' },
  { id: '7l_so08', question: '我国最大的咸水湖是（  ）', options: ['A. 青海湖', 'B. 纳木错', 'C. 色林错', 'D. 呼伦湖'], answer: 'A', explanation: '青海湖位于青海省，是我国最大咸水湖。', knowledgePoint: '湖泊', subject: '社会' },
  { id: '7l_so09', question: '我国夏季气温最低的地方是（  ）', options: ['A. 漠河', 'B. 青藏高原', 'C. 吐鲁番', 'D. 海南'], answer: 'B', explanation: '青藏高原海拔高，夏季气温最低。', knowledgePoint: '气温', subject: '社会' },
  { id: '7l_so10', question: '我国年降水量最多的地方是（  ）', options: ['A. 火烧寮', 'B. 吐鲁番', 'C. 漠河', 'D. 广州'], answer: 'A', explanation: '台湾火烧寮年均降水量达 6558 毫米。', knowledgePoint: '降水', subject: '社会' },
  { id: '7l_so11', question: '我国最大的盆地是（  ）', options: ['A. 四川盆地', 'B. 塔里木盆地', 'C. 准噶尔盆地', 'D. 柴达木盆地'], answer: 'B', explanation: '塔里木盆地面积约 53 万平方千米。', knowledgePoint: '地形', subject: '社会' },
  { id: '7l_so12', question: '我国最大的平原是（  ）', options: ['A. 华北平原', 'B. 长江中下游平原', 'C. 东北平原', 'D. 成都平原'], answer: 'C', explanation: '东北平原面积约 35 万平方千米。', knowledgePoint: '地形', subject: '社会' },
  { id: '7l_so13', question: '我国最大的岛屿是（  ）', options: ['A. 海南岛', 'B. 台湾岛', 'C. 崇明岛', 'D. 舟山岛'], answer: 'B', explanation: '台湾岛面积约 3.6 万平方千米。', knowledgePoint: '岛屿', subject: '社会' },
  { id: '7l_so14', question: '我国最大的群岛是（  ）', options: ['A. 西沙群岛', 'B. 南沙群岛', 'C. 舟山群岛', 'D. 东沙群岛'], answer: 'C', explanation: '舟山群岛位于浙江省，有岛屿 1390 个。', knowledgePoint: '群岛', subject: '社会' },
  { id: '7l_so15', question: '我国面积最大的省级行政区是（  ）', options: ['A. 西藏', 'B. 新疆', 'C. 青海', 'D. 内蒙古'], answer: 'B', explanation: '新疆维吾尔自治区面积约 166 万平方千米。', knowledgePoint: '行政区划', subject: '社会' },
  { id: '7l_so16', question: '我国人口最多的省级行政区是（  ）', options: ['A. 山东', 'B. 河南', 'C. 广东', 'D. 四川'], answer: 'C', explanation: '广东省常住人口超过 1.2 亿。', knowledgePoint: '人口', subject: '社会' },
  { id: '7l_so17', question: '我国最长的内流河是（  ）', options: ['A. 塔里木河', 'B. 黑河', 'C. 疏勒河', 'D. 伊犁河'], answer: 'A', explanation: '塔里木河全长 2179 千米。', knowledgePoint: '河流', subject: '社会' },
  { id: '7l_so18', question: '我国含沙量最大的河流是（  ）', options: ['A. 长江', 'B. 黄河', 'C. 珠江', 'D. 海河'], answer: 'B', explanation: '黄河中游流经黄土高原，含沙量大。', knowledgePoint: '河流', subject: '社会' },
  { id: '7l_so19', question: '我国唯一注入北冰洋的河流是（  ）', options: ['A. 黑龙江', 'B. 额尔齐斯河', 'C. 雅鲁藏布江', 'D. 怒江'], answer: 'B', explanation: '额尔齐斯河发源于新疆，注入北冰洋。', knowledgePoint: '河流', subject: '社会' },
  { id: '7l_so20', question: '我国的"五岳"中位于山东的是（  ）', options: ['A. 泰山', 'B. 华山', 'C. 衡山', 'D. 恒山'], answer: 'A', explanation: '东岳泰山位于山东省泰安市。', knowledgePoint: '名山', subject: '社会' },
  { id: '7l_so21', question: '世界上最高的山峰是（  ）', options: ['A. 乔戈里峰', 'B. 珠穆朗玛峰', 'C. 干城章嘉峰', 'D. 洛子峰'], answer: 'B', explanation: '珠穆朗玛峰海拔 8848.86 米。', knowledgePoint: '山峰', subject: '社会' },
  { id: '7l_so22', question: '我国跨经度最广的省级行政区是（  ）', options: ['A. 新疆', 'B. 西藏', 'C. 内蒙古', 'D. 甘肃'], answer: 'C', explanation: '内蒙古自治区东西跨经度约 29 度。', knowledgePoint: '行政区划', subject: '社会' },
  { id: '7l_so23', question: '我国少数民族最多的省级行政区是（  ）', options: ['A. 贵州', 'B. 云南', 'C. 广西', 'D. 四川'], answer: 'B', explanation: '云南省有 25 个少数民族。', knowledgePoint: '民族', subject: '社会' },
  { id: '7l_so24', question: '我国最大的经济特区是（  ）', options: ['A. 深圳', 'B. 珠海', 'C. 汕头', 'D. 海南'], answer: 'D', explanation: '海南经济特区面积约 3.54 万平方千米。', knowledgePoint: '经济', subject: '社会' },
  { id: '7l_so25', question: '我国的四大高原是（  ）', options: ['A. 青藏、内蒙古、黄土、云贵', 'B. 青藏、内蒙古、黄土、华北', 'C. 青藏、云贵、黄土、四川', 'D. 内蒙古、黄土、云贵、四川'], answer: 'A', explanation: '四大高原：青藏、内蒙古、黄土、云贵高原。', knowledgePoint: '地形', subject: '社会' },
  { id: '7l_so26', question: '我国的四大盆地是（  ）', options: ['A. 塔里木、准噶尔、柴达木、四川', 'B. 塔里木、柴达木、四川、华北', 'C. 准噶尔、柴达木、四川、东北', 'D. 塔里木、准噶尔、东北、华北'], answer: 'A', explanation: '四大盆地：塔里木、准噶尔、柴达木、四川盆地。', knowledgePoint: '地形', subject: '社会' },
  { id: '7l_so27', question: '我国的三大平原是（  ）', options: ['A. 东北、华北、长江中下游', 'B. 东北、华北、成都', 'C. 华北、长江中下游、成都', 'D. 东北、长江中下游、成都'], answer: 'A', explanation: '三大平原：东北、华北、长江中下游平原。', knowledgePoint: '地形', subject: '社会' },
  { id: '7l_so28', question: '我国夏季最热的地方是（  ）', options: ['A. 武汉', 'B. 南京', 'C. 吐鲁番', 'D. 重庆'], answer: 'C', explanation: '吐鲁番盆地夏季极端最高气温达 49.6℃。', knowledgePoint: '气温', subject: '社会' },
  { id: '7l_so29', question: '我国降水最多的季节是（  ）', options: ['A. 春季', 'B. 夏季', 'C. 秋季', 'D. 冬季'], answer: 'B', explanation: '受夏季风影响，降水集中在夏季。', knowledgePoint: '降水', subject: '社会' },
  { id: '7l_so30', question: '我国的"鱼米之乡"指的是（  ）', options: ['A. 东北平原', 'B. 华北平原', 'C. 长江中下游平原', 'D. 成都平原'], answer: 'C', explanation: '长江中下游平原河网密布，盛产稻米和淡水鱼。', knowledgePoint: '农业', subject: '社会' }
];

// 合并到 QUESTION_BANK
if (typeof QUESTION_BANK !== 'undefined') {
  QUESTION_BANK['7_lower'] = {
    '语文': CHINESE_7L,
    '数学': MATH_7L,
    '英语': ENGLISH_7L,
    '科学': SCIENCE_7L,
    '社会': SOCIAL_7L
  };
}